### ISSUE TITLE
how to user in chinese?

### ISSUE THREAD

**Issue by zqc0512** [XiaoguTech/grafana#1]
copy the pulic file is OK?
or need rebuild grafana?
the machine can't connect to network?
i know with grafana 5.2.1
@wangkanxiaogu  @zhongqin0820 
can give the .zip file to downloading with grafana new version?

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by zqc0512** [comment]
@zhongqin0820 能提供下build好的版本么？我现在用的5.2.1 机器连接不了互联网。

**Comment by zhongqin0820** [comment]
@zqc0512 
https://pan.baidu.com/s/1BvZCTmCIBEUEWOuQjxMdXQ
失效了告诉我

**Comment by zqc0512** [comment]
@zhongqin0820   this is only in windows.
can give in centos linux 7 .zip file? with 5.2.4 
thanks so.
